version: '3.7'

x-environment:
    &default-environment
    POSTGRES_USER: vscode
    POSTGRES_PASSWORD: notsecure
    POSTGRES_DB: tutorial
services:
    db:
        container_name: ${APP_NAME}-database
        image: ${DB_PROVIDER}:${DB_VERSION}
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MYSQL_DATABASE: ${DB_NAME}
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        volumes:
            - db_volume:/var/lib/mysql
        ports:
            - ${DB_PORT}:3306
        networks: 
            net:
                ipv4_address: 174.21.1.2
    app:
        build:
            context: ..
            dockerfile: .devcontainer/Dockerfile
            args: 
                - PHP_VERSION=${PHP_VERSION}
        container_name: ${APP_NAME}-www
        tty: true
        links:
            - db:${DB_PROVIDER}
        volumes:
            - ${APP_DIR}:/workspace
        ports:
            - ${HTTP_PORT}:80
            - ${HTTPS_PORT}:443
        networks:
            net:
                ipv4_address: 174.21.1.3
        user: root
        command: sleep infinity

networks: 
    net:
        driver: bridge
        ipam:
            config:
                - subnet: 174.21.1.0/24

volumes:
    db_volume:
